name: Build DevBuild
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
      - src/**
      - browser/**
      - scripts/build/**
      - package.json
      - pnpm-lock.yaml
env:
  FORCE_COLOR: true

jobs:
  DetermineRunner:
    name: Determine Runner
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-runner.outputs.runner-label }}
    steps:
      - name: Set runner
        id: set-runner
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.ETOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi
  Build:
    name: Build Equicord
    needs: DetermineRunner
    runs-on: ${{ needs.DetermineRunner.outputs.runner}}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web
        run: pnpm buildWeb --standalone

      - name: Build
        run: pnpm build --standalone

      - name: Generate plugin list
        run: pnpm generatePluginJson dist/plugins.json dist/plugin-readmes.json

      - name: Clean up obsolete files
        run: |
          rm -rf dist/*-unpacked dist/monaco Vencord.user.css vencordDesktopRenderer.css vencordDesktopRenderer.css.map

      - name: Upload DevBuild as release
        if: github.repository == 'Equicord/Equicord'
        run: |
          gh release upload latest --clobber dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
