name: Build DevBuild
on:
    push:
        branches:
            - main
        paths:
            - .github/workflows/build.yml
            - src/**
            - browser/**
            - scripts/build/**
            - package.json
            - pnpm-lock.yaml
env:
    FORCE_COLOR: true

jobs:
    Build:
        if: github.repository == 'Equicord/Equicord'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 19
              uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build web
              run: pnpm buildWeb --standalone

            - name: Build
              run: pnpm build --standalone

            - name: Generate plugin list
              run: pnpm generatePluginJson dist/plugins.json dist/plugin-readmes.json

            - name: Clean up obsolete files
              run: |
                  rm -rf dist/*-unpacked dist/monaco Vencord.user.css vencordDesktopRenderer.css vencordDesktopRenderer.css.map

            - name: Get some values needed for the release
              id: release_values
              run: |
                  echo "release_tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: Upload DevBuild as release
              run: |
                  gh release create devbuild-$RELEASE_TAG
                  gh release upload devbuild-$RELEASE_TAG --clobber dist/*
                  gh release edit devbuild-$RELEASE_TAG --title "DevBuild $RELEASE_TAG"
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
                  RELEASE_TAG: ${{ env.release_tag }}
