name: Release Browser Extension
on:
    push:
        tags:
            - v*

jobs:
    DetermineRunner:
        name: Determine Runner
        runs-on: ubuntu-latest
        outputs:
          runner: ${{ steps.set-runner.outputs.runner }}
        steps:
          - name: Determine which runner to use
            id: set-runner
            uses: benjaminmichaelis/get-soonest-available-runner@v1.1.0
            with:
              primary-runner: "self-hosted"
              fallback-runner: "ubuntu-latest"
              min-available-runners: 2
              github-token: ${{ secrets.ETOKEN }}

    Publish:
        if: github.repository == 'Equicord/Equicord'
        needs: DetermineRunner
        runs-on: ${{ needs.DetermineRunner.outputs.runner }}

        steps:
            - uses: actions/checkout@v3

            - name: check that tag matches package.json version
              run: |
                  pkg_version="v$(jq -r .version < package.json)"
                  if [[ "${{ github.ref_name }}" != "$pkg_version" ]]; then
                      echo "Tag ${{ github.ref_name }} does not match package.json version $pkg_version" >&2
                      exit 1
                  fi

            - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 19
              uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build web
              run: pnpm buildWeb --standalone

            - name: Publish extension
              run: |
                  cd dist/chromium-unpacked
                  pnpx chrome-webstore-upload-cli@2.1.0 upload --auto-publish
              env:
                  EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
